# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e005a4e5c42e74b722daafe95c2a8f3a6a57089fcbfc7e866b233c150c5486ebb9d2daa6276b82e85639ed4a959295662ce8066da2d4ba1b74064d44b5c00f

test:
  secret_key_base: eb7b3e8fe367237d7e3000423d52e766035c51f9980e257b7d1b6ef35cd838afb546bab3b3a5481bac90224d28897e8e559603c0c94623e9888a19a8f70f3926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
